apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/operators/strimzi-kafka-operator/operator/overlays/stable?ref=v0.11
